name: Check IPv6 Support and Curl Google

on:
  push:
  workflow_dispatch:

jobs:
  check-ipv6-and-curl:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check IPv6 support
      run: |
        echo "Checking IPv6 support..."
        if [ -f /proc/net/if_inet6 ]; then
          echo "IPv6 is supported"
          ip -6 a
        else
          echo "IPv6 is NOT supported"
          exit 1
        fi
        echo "Testing IPv6 connectivity..."
          if ping6 -c 4 ipv6.google.com; then
            echo "IPv6 connectivity looks good."
          else
            echo "IPv6 connectivity test failed."
            exit 1  # Fail the job if IPv6 is not reachable
          fi
        
    - name: Curl Google over IPv6
      run: |
        echo "Curling Google over IPv6..."
        # Use the '-6' flag to force curl to use IPv6
        # Use the '--verbose' flag to get detailed information about the request and response
        curl -6 --verbose https://www.google.com

